import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import MouseTrail from "@/components/MouseTrail";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DefiForge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MouseTrail />

        {children}
      </body>
    </html>
  );
}
